title: Bruce Moran, Bioinformatics

author: Bruce Moran

theme: jekyll-theme-minimal

social-network-links:
  email: "bruce01campus@gmail.com"
  github: brucemoran
  twitter: bruler0111
  ORCID: 0000-0002-7266-0265

share-links-active:
  twitter: true
  github: true
  ORCID: true
